#!/usr/bin/env python3
import asyncio
import sys

from gql.cli import get_parser, main

# Get arguments from command line
parser = get_parser(with_examples=True)
args = parser.parse_args()

try:
    # Execute the script
    exit_code = asyncio.run(main(args))

    # Return with the correct exit code
    sys.exit(exit_code)
except KeyboardInterrupt:
    pass
