name: Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install tox
    - name: Run lint and static type checks
      run: tox
      env:
        TOXENV: flake8,black,import-order,mypy,manifest
